name: untitled
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  #svg
  flutter_svg: ^2.0.7
  #di 
  get_it: ^8.0.2
  #state manager
  flutter_bloc: ^9.1.1
  # Equtable
  equatable: ^2.0.7
  # rest api
  dio: ^5.4.3+1
  dartz: ^0.10.1
  go_router: ^14.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

